version: "3"

services:
  benki:
    container_name: benki
    build:
      context: .
      dockerfile: Dockerfile
    image: benki-image:latest
    command: air
    ports:
      - 8080:8080
    volumes:
      - .:/app
    tty: true
    environment:
      - DB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8443:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../front/dist:/var/www
      - ./nginx/static:/etc/nginx/static
      - ./nginx/keys:/etc/nginx/keys
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway

  linebot:
    build:
      context: ./linebot
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3012:3012"

  # conversation:
  #   build:
  #     context: ./conversation
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3013:3013"

  image:
    image: node
    container_name: image
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./backend/.aws:/root/.aws:ro
    working_dir: /app
    command: ["npm", "run", "dev-ts"]

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint:
      - "/bin/sh"
      - "-c"
    command:
      - "mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
        mc mb myminio/benkibenki;
        mc cp ./image/init_data/* myminio/benkibenki;
        exit 0;"
    volumes:
      - ./init_data:/image/init_data
volumes:
  mongodb_data:
  minio_data:
